# Generated by Django 4.2 on 2025-01-17 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProgramStudi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kode_programstudi", models.CharField(max_length=3)),
                ("nama_programstudi", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Mahasiswa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=50)),
                ("nim", models.CharField(max_length=10)),
                (
                    "jenis_kelamin",
                    models.CharField(
                        choices=[
                            ("Laki-laki", "Laki-laki"),
                            ("Perempuan", "Perempuan"),
                            ("Lainnya", "Lainnya"),
                        ],
                        max_length=10,
                    ),
                ),
                ("alamat", models.TextField()),
                ("telephone", models.CharField(max_length=12)),
                (
                    "programstudi",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kampus.programstudi",
                    ),
                ),
            ],
        ),
    ]
